-- Dados fictícios do protótipo, separados de escolas e documentos reais.
create table public.dados_demonstracao (
  chave text primary key check (chave ~ '^[a-z][a-z0-9_]{1,62}$'),
  conteudo jsonb not null check (jsonb_typeof(conteudo) in ('object', 'array')),
  versao integer not null default 1 check (versao > 0),
  updated_at timestamptz not null default now()
);
create trigger dados_demonstracao_atualiza before update on public.dados_demonstracao for each row execute procedure app.touch_updated_at();
alter table public.dados_demonstracao enable row level security;
create policy "dados demonstracao leitura publica" on public.dados_demonstracao for select to anon, authenticated using (true);
grant select on public.dados_demonstracao to anon, authenticated;

insert into public.dados_demonstracao (chave, conteudo) values
('formulario_exemplo', '{"dados":{"escola":"Escola Estadual Horizonte do Saber","inep":"31123456","municipio":"Divinópolis","sre":"Divinópolis","direcao":"Marta Ferreira Lopes","especialista":"Rita de Cássia Andrade","endereco":"Rua das Palmeiras, 210 — Centro","ato":"Decreto nº 22.145, de 12/03/1982","turnos":"manhã e tarde","estudantes":"482","turmas":"18","colegiado":"João Batista de Souza","vigencia":"2026–2028"},"selecoes":{"etapas":["efai","efaf"],"mods":["parcial","esp"],"infra":["salas","biblio","labinf","quadra","srm","refeit","acess","tec"],"temas":["ambiental","dh","etnico","digital","paz","vida"],"principios":["integral","inclusiva","equidade","democratica","antirracista","protagonismo"],"metodos":["projetos","ativas","rodas","tdic","colaborativa"]},"textos":{"tMissao":"Missão — Garantir que nenhum estudante saia do 9º ano sem ler com autonomia. Visão — Ser reconhecida, até 2028, como escola de referência em alfabetização e permanência.","tDiagnostico":"O abandono de 3,5% nos Anos Finais concentra-se no 8º e no 9º ano. A distorção de 21% no 8º ano decorre de retenções acumuladas."},"indicadores":{"ano":"2025","idebAI":"5,8","idebAF":"4,7","idebAno":"2023","proalfa":"62% no padrão recomendado","proeb":"LP 9º ano — 34% no padrão baixo","clima":"pertencimento","aee":"14","docentes":"32","etapas":{"efai":{"mat":"214","apr":"93,1","rep":"5,4","aba":"1,5","dis":"9,0"},"efaf":{"mat":"268","apr":"88,4","rep":"8,1","aba":"3,5","dis":"21,0"}}},"versao":2,"origem":"PPP-2024-0031-D4KM"}'::jsonb),
('registros_painel', '[
{"protocolo":"PPP-2026-0001-K3Q9","versao":1,"escola":"Escola Estadual Horizonte do Saber","inep":"31123456","municipio":"Divinópolis","sre":"Divinópolis","status":"Em andamento","pct":62,"assinadas":0,"totalAssin":0,"ressalvas":0,"ata":false,"atualizadoEm":"02/09/2026 15:40"},
{"protocolo":"PPP-2026-0002-B7RT","versao":1,"escola":"Escola Estadual Padre João Ribeiro","inep":"31123457","municipio":"Divinópolis","sre":"Divinópolis","status":"Em assinatura","pct":100,"assinadas":3,"totalAssin":8,"ressalvas":1,"ata":false,"atualizadoEm":"01/09/2026 09:12"},
{"protocolo":"PPP-2026-0003-M2XL","versao":2,"escola":"Escola Estadual do Campo Boa Esperança","inep":"31123458","municipio":"Santo Antônio do Monte","sre":"Divinópolis","status":"Assinado","pct":100,"assinadas":9,"totalAssin":9,"ressalvas":0,"ata":false,"atualizadoEm":"29/08/2026 17:05"},
{"protocolo":"PPP-2026-0004-Z8KD","versao":1,"escola":"Escola Estadual Anísio Teixeira","inep":"31123459","municipio":"Nova Serrana","sre":"Divinópolis","status":"Concluído","pct":100,"assinadas":11,"totalAssin":11,"ressalvas":2,"ata":true,"atualizadoEm":"28/08/2026 11:20"},
{"protocolo":"PPP-2026-0005-Q4WP","versao":1,"escola":"Escola Estadual Maria da Conceição","inep":"31123460","municipio":"Itaúna","sre":"Divinópolis","status":"Enviado para homologação","pct":100,"assinadas":7,"totalAssin":7,"ressalvas":0,"ata":true,"atualizadoEm":"26/08/2026 14:00"},
{"protocolo":"PPP-2026-0006-H9NF","versao":1,"escola":"Escola Estadual Carlos Drummond","inep":"31200011","municipio":"Belo Horizonte","sre":"Metropolitana A","status":"Em andamento","pct":35,"assinadas":0,"totalAssin":0,"ressalvas":0,"ata":false,"atualizadoEm":"02/09/2026 08:44"},
{"protocolo":"PPP-2026-0007-T5VC","versao":1,"escola":"Escola Estadual Serra Verde","inep":"31200012","municipio":"Belo Horizonte","sre":"Metropolitana A","status":"Enviado para homologação","pct":100,"assinadas":10,"totalAssin":10,"ressalvas":0,"ata":true,"atualizadoEm":"22/08/2026 10:30"},
{"protocolo":"PPP-2026-0008-J6DR","versao":1,"escola":"Escola Estadual do Triângulo","inep":"31300021","municipio":"Uberlândia","sre":"Uberlândia","status":"Em assinatura","pct":100,"assinadas":5,"totalAssin":12,"ressalvas":1,"ata":false,"atualizadoEm":"31/08/2026 16:18"},
{"protocolo":"PPP-2026-0009-P1LS","versao":1,"escola":"Escola Estadual Quilombola Vila Nova","inep":"31400031","municipio":"Montes Claros","sre":"Montes Claros","status":"Em andamento","pct":48,"assinadas":0,"totalAssin":0,"ressalvas":0,"ata":false,"atualizadoEm":"30/08/2026 13:55"},
{"protocolo":"PPP-2026-0010-C3YB","versao":1,"escola":"Escola Estadual Norte de Minas","inep":"31400032","municipio":"Montes Claros","sre":"Montes Claros","status":"Concluído","pct":100,"assinadas":8,"totalAssin":8,"ressalvas":0,"ata":true,"atualizadoEm":"27/08/2026 09:02"}]'::jsonb),
('acessos_exemplo', '[{"email":"dire.divinopolis@educacao.mg.gov.br","nome":"Equipe DIRE Divinópolis","perfil":"regional","sre":"Divinópolis","situacao":"ativo","ultimoAcesso":"02/09/2026 10:11","comSenha":true},{"email":"dire.metropolitana.a@educacao.mg.gov.br","nome":"Equipe DIRE Metropolitana A","perfil":"regional","sre":"Metropolitana A","situacao":"ativo","ultimoAcesso":"","comSenha":true}]'::jsonb)
on conflict (chave) do update set conteudo = excluded.conteudo, versao = public.dados_demonstracao.versao + 1, updated_at = now();
